name: workflow
on:
  push:
    brnaches:
      - master
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: apt-get install --no-install-recommends -y asciidoc
      - run: git clone https://git.archlinux.org/arch-install-scripts.git arch
      - run: cd arch && make arch-chroot
      - run: mkdir /mnt || true
      - run: mount --bind /mnt /mnt
      - run: ./setup-pacstrap.sh
