name: workflow
on:
  push:
    brnaches:
      - master
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: sudo apt install -y autopoint arch-install-scripts
      - run: git clone https://git.archlinux.org/pacman.git/ pacman && cd pacman && ./autogen.sh && ./configure && make && sudo make install && cd ..
      - run: sudo mkdir /mnt || true
      - run: sudo mount --bind /mnt /mnt
      - run: sudo ./setup-pacstrap.sh
