name: workflow
on:
  push:
    brnaches:
      - master
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: sudo apt install -y squashfs-tools
      - run: sudo curl -LO http://mirror.rackspace.com/archlinux/iso/latest/arch/x86_64/airootfs.sfs
      - run: sudo unsquashfs airootfs.sfs
      - run: sudo mount --bind squashfs-root squashfs-root
      - run: sudo mount -t proc none squashfs-root/proc
      - run: sudo mount -t sysfs none squashfs-root/sys
      - run: sudo mount -o bind /dev squashfs-root/dev
      - run: sudo mount -o bind /dev/pts squashfs-root/dev/pts
      - run: sudo mount --bind squashfs-root/mnt squashfs/mnt
      - run: sudo cp -L /etc/resolv.conf squashfs-root/etc
      - run: sudo cp setup.sh squashfs-root
      - run: sudo chroot squashfs-root bash ./setup.sh
